### ISSUE TITLE
What contributes to the slowness of send?

### ISSUE THREAD

**Issue by mopleen** [SodiumFRP/sodium#38]
Hi!
I did some simple benchmarks on single-threaded version of the library. I tried to send 1 million integers into behavior_sink and it took almost 2 seconds. When it's wrapped in transaction, it's well over 2 seconds. Could you please write (if you know) why it is such a slow operation?

P.S. I didn't expect to find that sending the same int propagates update. Could you please explain for what reasons it's made like this? I expected that sending the same value (not changing the behavior) wouldn't result in firing updates() event of that behavior (and all dependent behaviors).

**Comment by the-real-blackh** [comment]
The performance of Sodium could be dramatically improved, but the work hasn't been done. There are many reasons why it's slow. Probably the main one is the fact that it uses a priority queue during processing, but the order of processing could be pre-compiled and it would be hugely faster. 

Parallelism is something else that would need to be considered in an improved implementation. 

Rather than a coarse granularity mutex, a transaction could use a software transactional memory approach. The sequence of two transactions running on different threads only needs to be decided if they conflict.

Another way to speed the system up would be to use some form of lazy propagation instead of pushing every value all the way through.

To sum up: Currently Sodium is really a reference implementation. The potential for speeding it up is huge, but the amount of work could be considerable. We have five programming languages to think about. It might even be a good idea to keep the reference implementation in each language, and write a separate optimized implementation, and use the first one to verify the second one.

Also, at the moment, Sodium isn't used widely enough for performance to be much of an issue in practice, but that will change.

Note: I am seriously considering taking updates() and value() out or limiting them to a new type for semantic reasons.

On not propagating the same value: Firstly, we can't necessarily assume that all values have an equality operation, or that the operation is fast. Comparing equality for large data structures, for example, would be very inefficient. The presence of updates() means that not changing a Cell/Behavior has semantic implications, and we can't allow that: The whole point of FRP is that it is semantically simple and clean. updates() is very problematic in a number of ways.

**Comment by mopleen** [comment]
Thank you for such a detailed reply! I'm interested in single threaded version, so mutex and parallelism are not much of an issue for me. But it's very good that library supports single threaded mode that doesn't drag down performance with unnecessary locks!

Without updates(), how is it supposed to extract values from behaviors on the outputs of the system? I can only think of snapshot(), but let's consider this simple example. There is a behavior and its value is displayed somewhere somehow. Now it's easy to listen to its updates() event. Do you suggest dragging some other event along with behavior to indicate changes in that behavior?

About the same value, thank you for confirming my thoughts about equality operation and its potential cost or absence. For some reason I expected it to magically work and not fire updates() when it hasn't really changed.

**Comment by the-real-blackh** [comment]
Note: I'm going to change the names of behavior -> cell and event -> stream. I haven't done it in the C++ implementation yet. This is at the urging of the publisher since "event" and "behavior" have OOP meanings. So I'll use the new names....

To listen to a cell, we would add listenValue() / listenUpdates() methods so value() and updates() would still exist, but only in the "dirty" world of I/O.

Dragging a stream along with cell is actually what we're doing now, but it's happening behind the scenes. So one solution is to take updates() out of cell and have a new class, perhaps CellStream or DiscreteCell that does what cell does now and exposes updates() / value().
