### ISSUE TITLE
A question on hold

### ISSUE THREAD

**Issue by JamesTimms** [SodiumFRP/sodium#48]
Hi,

I'm working with the Java part of the library and am trying to run this.

    public void testComplicatedStuff() {
        StreamSink<Integer> flowOfData = new StreamSink<>();
        Cell<String> value = flowOfData
                .filter(number -> number != 1)
                .hold(3)
                .updates()
                .map(number -> number.toString())
                .filter(string -> !string.equals("1"))//Even when this line isn't here
                .hold("1");//This should fail.

        assertNotSame("1", value.sample());//<--- should not be the same.
        assertEquals(3, value.sample());

        flowOfData.send(new Integer(2));
        assertEquals("2", value.sample());//These two lines of code work.
    }

Currently .hold("1"); lets value start with "1" but I was expecting .filter(string -> !string.equals("1")) to prevent this initial value. So either the initial value should be null or 3?
Am I using the library wrong or is this an issue at all?

Additionally if I removed the line .filter(string -> !string.equals("1")) would it be correct to expect .filter(number -> number != 1) to prevent "1" from being used?

**Comment by kentuckyfriedtakahe** [comment]
hold("1") creates a Cell containing the initial value of "1". The filter(string -> !string.equals("1")) filters out the event coming into the Cell but there are no events being fired in your construction code. Consider that the filter is upstream of the hold and has no effect on the initial value.

updates() does not fire an update until you call send(new Integer(2)). If you had used values() (inside an explicit transaction) you would have seen an initial value of "3" because values() fires the current value.

The filter(string -> !string.equals("1")) has no effect because the first filter blocks values of 1 from getting to that point.

**Comment by JamesTimms** [comment]
Ah so the Cell's initial value from hold("1") is set regardless of any filters.
So I'm guessing only way around this is to hold(null) then send my initial value if I want the filters to prevent any incorrect values from getting through.

Thanks.

**Comment by kentuckyfriedtakahe** [comment]
You are correct. However some more general advice would be:

* Avoid both values() and updates() unless you have a compelling reason to use them.
* Use java.util.Optional instead of null values. It makes it much clearer which values are nullable.

Another advantage of Optional is that you can call Optional.map() to apply a function to a value only when it is present.

**Comment by JamesTimms** [comment]
Oh ok thank you.
