### ISSUE TITLE
Scala & Java version both use same package

### ISSUE THREAD

**Issue by MichaelJAllen** [SodiumFRP/sodium#49]
Both the _Java_ and _Scala_ versions of the API replicate class and package names, leading to potential naming conflicts. For example, if a _Java_ library that relies upon the _Java_ flavor of the library is employed by a _Scala_ application that uses the _Scala_ flavor of the library, then there will be two conflicting sets of elements sharing the _sodium_ package required by the application.

These libraries, and any other _JVM_ flavors of the library, should have unique package names to avoid such conflicts.

**Comment by kentuckyfriedtakahe** [comment]
You could work around this problem by using a separate ClassLoader for each library. I don't see how this is different from the problem you'd get if two libraries depended on different versions of a common library. The downside of the ClassLoader approach is that you end up with two different classes with the same fully qualified name.

Perhaps a better solution, should this problem arise, would be to make the Scala version backwards compatible with the Java version so that it will pass both the Scala and Java test suites. This would avoid the problem of having incompatible Scala and Java versions of the same classes.

**Comment by butlermh** [comment]
@MichaelJAllen That's my fault, I just used the same package name. When modified the code for Scala I just saw it as being a learning tool. Maybe that's wrong though because there does seem to be quite a bit of interest around this.

To put it more positively any suggestions on what would be a good package name for the Scala version? I don't think `scala.sodium` is good - because `scala` is used by Typesafe - how about `sodium.scala` ? If we can come up with consensus I can submit a patch.

@kentuckyfriedtakahe I am not so keen on the idea of backward compatibility because I think that would make the Scala version ugly. Actually interop between Java and Scala is often harder than people think. The Java converter classes in Scala hide some of it,  but when Scala people use Java first libraries they often "pimp" them because they don't like the Java interface. This seems to have the side-effect that there are plenty of tools out there that use outdated variants of libraries, because they use a thin Scala wrapping layer that hasn't been updated - see all the abandoned Coda Hale libraries. In my experience making Scala code so it can be called by Java is painful .. one way to do it is using Java classes - although if anyone has some better ideas / pointers here that would be helpful. So I think there is some advantage in having a "pure" Scala version. 

Note I am not claiming the current Scala version is pretty .. it is a hack job I did over a weekend as an exercise to practice my Scala, before I had read the book - because the Java version seems to be based on the C# version, and the Scala version is based on the Java version, so it will copy inefficiencies of those two ....

In fact I need to go back because some fixes just came in for the Java version so I need to check they are in the Scala one too ... but I was surprised though, because even though the Java one is using Java 8, the Scala one is quite a bit simpler.

**Comment by MichaelJAllen** [comment]
@kentuckyfriedtakahe: I like the idea of somehow linking the _Scala_ and _Java_ versions of the library, which I think would make maintainability a lot easier. However, I agree with @butlermh - using a _Java_ API interface in _Scala_ is ugly (_Scala_ programmers do not like `null`s, or using _Java_ collections, and I don't think _Scala_ function objects are yet compatible with their equivalents in _Java 8_), while providing a _Java_ interface to a _Scala_ API is nontrivial. Perhaps having a core library written in either language (_Scala_ would seem a more natural alternative since it doesn't require a lot of tedious _Java_ boilerplate) with separate _Java_ and _Scala_ interfaces is the way to go?

In the meantime, having separate pure libraries isn't the worst solution, and I wouldn't be averse to using the _Scala_ API via a `sodium.scala` package.

Personally, I'm a lot more interested in a _Scala FRP_ API than in one for _Java_ (since learning _Scala_, _Java_ looks increasingly like an ugly hodge-podge of ideas with hideous syntax). I've only just discovered _Sodium_, but I like what I've seen so far. Thanks to both of you for your efforts!

**Comment by kentuckyfriedtakahe** [comment]
@butlermh The Java version is not based on the C# version. It was written after the Haskell and C++ versions but before the C# version was contributed. I'll make my points a little more clear:

1. This is a hypothetical problem that doesn't require a name change to fix.
2. Even if you do change the names, you will end up with two FRP engines in one project.
3. A better although more difficult solution would be to make one FRP engine that serves both languages.

It doesn't look like a problem that is necessary to solve at this point. If the problem comes up then what we'll probably need to solve it by making one FRP engine serve both languages. There is a big upside to having one Cell object and one Stream object that are the same thing in both languages. It would make sense to write it in Scala because Scala knows about Java but Java does not know about Java.

Changing the name of the library doesn't fix the core problem and you don't need separate names if you use separate ClassLoaders.

@MichaelJAllen I'm thinking in terms of adding Java compatible primitives so you can for example call lift() with either a Java or Scala lambda. We should all be avoiding null and it may make sense to add a null check to the Java classes anyway. I have done some programming in Scala but I am by no means an expert. My main point is that it looks like a problem that can be solved when it becomes an issue.
