### ISSUE TITLE
Why Cell must follow non-detectability of steps rule?

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#58]
In the book there is only one mention of this rule. I dont understand why it is important for cell? In leatest commits you removed `Cell.collect` because of it, but how about `Cell.listen`? It violates this rule too.

PS: M.b. you should move `collect` to `Operational`? It is useful method for making FSM. And `listen` too.

**Comment by the-real-blackh** [comment]
This rule is a fundamental part of Conal Elliott's design for FRP, in which Behavior (Cell) and Event (Stream) represent separate concepts with no overlap. Cell.listen does violate it but it's less problematic because once you're in I/O you can't go back - send() isn't allowed in a handler. It didn't seem necessary to make that part of the API ugly. update() and values() are the only ones where there's a serious risk of using them in a way that isn't legitimate.

As for collect(), there are lots of helpers we could add. I want to be very selective about it, and I want to add them if they're really compelling. There are many things I would prioritize above Cell.collect().
