### ISSUE TITLE
Java: Publicate lib on Maven Central.

### ISSUE THREAD

**Issue by romansl** [SodiumFRP/sodium#63]
This is a standard and convenient way to spread libraries.

Just follow this guide: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by the-real-blackh** [comment]
Great idea. I will.

**Comment by braghome** [comment]
:+1:  ditto would then easily fit my workflow if on maven

**Comment by the-real-blackh** [comment]
Done, but examples re-work and book re-work not quite complete yet. See here:

https://repo.maven.apache.org/maven2/nz/sodium/sodium/

Since I've never done this before I'd appreciate any feedback about how well it works. The 'battle' example should work:

  cd book/battle/java
  mvn test -Pbattle
  mvn test -Pshift
  mvn test -Pshift2
