### ISSUE TITLE
GC problems with GHCJS

### ISSUE THREAD

**Issue by jhegedus42** [SodiumFRP/sodium#70]
I just recently compiled the ghcjs-examples (https://github.com/ghcjs/ghcjs-examples/), and for example the mouse example only works for 2 seconds. http://www.viizio.com/~joco/weblog/mouse/mouse.jsexe/ and any example that uses Sodium works only for 2 seconds.  Examples that do not use Sodium work OK. Luite said on irc that this might be some kind of GC issue.

This compilation can be reproduced by using this docker image : https://registry.hub.docker.com/u/jhegedus42/mouse-example-works-for-2seconds/

**Comment by the-real-blackh** [comment]
I know about these problems. I believe the issue is to to do with GHCJS implementing finalizers differently - but still correctly - from how GHC implements them. In other words, Sodium relies on GHC implementation, not the actual specification. The finalizers are running before we want them to and de-registering listeners. At least, that's what I think is happening.

This is now on my to-do list and I will get to it when I can.

**Comment by the-real-blackh** [comment]
It seems Sodium is broken on ghc-7.10.2. MVar's mkWeakIORef doesn't work like it used to. The Haskell, C# and Scala versions of Sodium all need a bit of work. I'm working on a unified test system to get them all fixed up.

**Comment by jhegedus42** [comment]
As far as I remember - I used ghc 7.8 to compile this. Not 100% sure though.

**Comment by alios** [comment]
Hi had the same problem some time ago (documented it in the ghcjs) issue tracker here: 
https://github.com/ghcjs/ghcjs/issues/296

There is a hack availible (disabling the call to the finalizers in the rts), which keeps sodium working, but that seems to lead to memory leaks. It is ok for me at the moment working on my code, but hoping that the problem can be fixed.

**Comment by HeinrichApfelmus** [comment]
Hi, Heinrich here. Since Stephen has [deprecated][1] the Haskell (!) version of sodium in favor of reactive-banana, I guess I should jump in here.

As far as I know, reactive-banana works well with native GHC 7.10. Unfortunately, it currently doesn't work with GHCJS. The short version is that the GHCJS implementation of the `System.Mem.Weak` module for weak pointers is different from the official semantics. If you file a bug report on the [reactive-banana][2] repo, I can look into implementing a workaround.


  [1]: http://blog.reactiveprogramming.org/?p=258
  [2]: https://github.com/HeinrichApfelmus/reactive-banana

**Comment by the-real-blackh** [comment]
Heinrich: Luite has told me that GHCJS's implementation of System.Mem.Weak is in line with the official semantics (as described in the GHC documentation) but not with the standard GHC implementation. Sodium depended on the GHC behaviour and most likely Reactive Banana does too. If the official semantics make Reactive Banana impossible (which could well be true) then there could be a case for asking GHC to change the specification.

Also it may be worth investigating whether Control.Concurrent.MVar.mkWeakMVar can be used to solve the problem.

Thank you for taking this up because I don't have time for it at the moment. I think GHCJS is an impressive and hugely important project and FRP is of course also important, so I appreciate you giving it your attention.

**Comment by HeinrichApfelmus** [comment]
@the-real-blackh: Ah, you probably mean weak pointers to ordinary Haskell values that have no identity? That is actually fine in my case. [According to Luite][1], the issue that I'm facing is indeed something were he deviated from the official semantics ([full thread][2]).

In any case, I'll look into this.

  [1]: https://www.reddit.com/r/haskell/comments/3ly4pe/which_frontend_library_to_use_with_ghcjs/cvbrc34
  [2]: https://www.reddit.com/r/haskell/comments/3ly4pe/which_frontend_library_to_use_with_ghcjs/cvb5t2a

**Comment by alios** [comment]
@HeinrichApfelmus yesterday evening I ported my code from reactive banana (1.0 api). First of all: feels very well and transition was smooth. What I can say now - same effect as with sodium and described above works for ~2sec then stops doing things.

If I find the time I'll try to extract a minimal example which shows this effect and post a bug report in the reactive-banana tracker.

**Comment by HeinrichApfelmus** [comment]
I have created issue HeinrichApfelmus/reactive-banana#109 to keep track of this on the reactive-banana side.

**Comment by the-real-blackh** [comment]
This has been fixed I believe. Yay!
